config/routes.rb
Pln::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root :to => redirect("/admin")

  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :notes
  has_many :goals
  
  # after_create { |admin| admin.send_reset_password_instructions }
  
  def name
    self.email
  end
 
  def password_required?
    new_record? ? false : super
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :member
  belongs_to :admin_user

  scope :near_due, where(:duedate => Date.yesterday..Date.today.next_month)
  scope :future, lambda { where("duedate >= ?", Time.now) }
  scope :past, lambda { where("duedate < ?", Time.now) }

  FUTURE = "future"
  PAST = "past"

  attr_accessible :body, :member, :member_id, :admin_user, :admin_user_id, :complete, :duedate, :location, :updated_at, :create_at

  validates :body, :member, :location, :duedate, :presence => true

  def state
    self.duedate < Time.now ? PAST : FUTURE
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :member
  belongs_to :admin_user

  scope :incomplete, lambda { where("complete = ?", false) }
  scope :completed, lambda { where("complete = ?", true) }
  scope :near_due, where(:duedate => Date.yesterday..Date.today.next_month)

  COMPLETE = "complete"
  INCOMPLETE = "incomplete"

  attr_accessible :body, :member, :member_id, :admin_user, :admin_user_id, :complete, :duedate, :updated_at, :create_at

  validates :body, :member, :presence => true

  def state
    self.complete ? COMPLETE : INCOMPLETE
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  # constants
  GENDERS = ['MALE', 'FEMALE', 'TRANSGENDER', 'OTHER']
  DIAGNOSES = ['HIV+', 'AIDS', 'HIV+ & Hep C']
  ETHNICITIES = ['ABORIGINAL', 'STATUS', 'NON-ABORIGINAL', 'UNDISCLOSED']
  PROVINCES = ['ALBERTA', 'BRITISH COLUMBIA', 'MANITOBA', 'NEW BRUNSWICK', 'NEWFOUNDLAND AND LABRADOR', 'NOVA SCOTIA', 'ONTARIO', 'PRINCE EDWARD ISLAND', 'QUEBEC', 'SASKATCHEWAN', 'NORTHWEST TERRITORIES', 'NUNAVUT', 'YUKON']

  has_many :notes, :dependent => :destroy
  has_many :goals, :dependent => :destroy

  attr_accessible :name, :birthdate, :gender, :address, :city, :province, :postalCode, :telephone, :carecard, :sin, :ethnicity, :diagnosis, :arv, :arvDate, :doctor, :doctorPhone, :placeDiagnosis, :dateDiagnosis, :active, :methadone, :emergency_contact_name, :emergency_contact_phone

  validates :name, :gender, :ethnicity, :diagnosis, :presence => true
  validates :gender, :inclusion => { :in => GENDERS }
  validates :ethnicity, :inclusion => { :in => ETHNICITIES }
  validates :diagnosis, :inclusion => { :in => DIAGNOSES }

  def self.incomplete
    Member.all.select { |m|
      m.name.blank? || m.gender.blank? || m.ethnicity.blank? || m.diagnosis.blank? || m.sin.blank? || m.address.blank? || m.city.blank? || m.birthdate == nil || m.province.blank? || m.postalCode.blank? || m.telephone.blank? || m.carecard.blank? || m.doctor.blank? || m.doctorPhone.blank? || m.emergency_contact_name.blank? || m.emergency_contact_phone.blank?}
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :member
  belongs_to :admin_user

  attr_accessible :body, :member, :member_id, :admin_user, :admin_user_id, :updated_at, :create_at

  validates :body, :member, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
  def snippet(thought, wordcount=10) 
    thought.split[0..(wordcount-1)].join(" ") + (thought.split.size > wordcount ? "..." : "") 
  end 
end

app/views/admin/appointments/_form.html.erb
<%= semantic_form_for [:admin, @appointment] do |f| %>
  <%= f.inputs "Appointment Details" do %>
    <%= f.input :member, :include_blank => false %>
    <%= f.input :admin_user_id, :as => :hidden, :value => current_admin_user.id %>
    <%= f.input :duedate, :label => "Date/Time", :as => :datetime, :order => [:month, :day, :year], :start_year => 2010, :minute_step => 5, :ampm => true, :prompt => {:day => 'Day', :month => 'Month', :year => 'Year', :hour => 'Hour', :minute => 'Minute'} %>
    <%= f.input :location, :label => "Location" %>
    <%= f.input :body, :label => "Description" %>
  <% end %>
  <%= f.buttons :commit %>
<% end %>

app/views/admin/goals/_form.html.erb
<%= semantic_form_for [:admin, @goal] do |f| %>
  <%= f.inputs "Goal Details" do %>
    <%= f.input :member, :include_blank => false %>
    <%= f.input :admin_user_id, :as => :hidden, :value => current_admin_user.id %>
     <%= f.input :duedate, :label => "Due Date (blank for N/A)", :as => :datetime, :order => [:month, :day, :year], :start_year => 2010, :minute_step => 5, :ampm => true, :prompt => {:day => 'Day', :month => 'Month', :year => 'Year', :hour => 'Hour', :minute => 'Minute'} %>
    <%= f.input :body, :label => "Description" %>
    <%= f.input :complete, :as => :select, :collection => [["False", false], ["True", true]], :include_blank => false %>
  <% end %>
  <%= f.buttons :commit %>
<% end %>

app/views/admin/members/_form.html.erb
<%= semantic_form_for [:admin, @member] do |f| %>
  <%= f.inputs "Details" do %>
    <%= f.input :name, :label => "Name" %>
    <%= f.input :birthdate, :as => :date, :order => [:month, :day, :year], :start_year => 1900 %>
    <%= f.input :gender, :as => :select, :collection => Member::GENDERS %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :province, :as => :select, :collection => Member::PROVINCES %>
    <%= f.input :postalCode, :label => "Postal Code" %>
    <%= f.input :telephone %>
    <%= f.input :carecard, :label => "Care Card" %>
    <%= f.input :sin, :label => "SIN" %>
    <%= f.input :ethnicity, :as => :select, :collection => Member::ETHNICITIES %>
    <%= f.input :diagnosis, :as => :select, :collection => Member::DIAGNOSES %>
    <%= f.input :placeDiagnosis, :label => "Place of Diagnosis" %>
    <%= f.input :dateDiagnosis, :label => "Date of Diagnosis", :as => :date, :order => [:month, :day, :year], :start_year => 1900 %>
    <%= f.input :arv, :label => "Anti-Retrovirals?", :as => :select, :collection => [["False", false], ["True", true]], :include_blank => false %>
    <%= f.input :arvDate, :label => "ARV Date", :as => :date, :order => [:month, :day, :year], :start_year => 1900 %>
    <%= f.input :methadone, :label => "Methadone?", :as => :select, :collection => [["False", false], ["True", true]], :include_blank => false %>
    <%= f.input :doctor %>
    <%= f.input :doctorPhone, :label => "Doctor Telephone" %>
    <%= f.input :emergency_contact_name, :label => "Emergency Contact" %>
    <%= f.input :emergency_contact_phone, :label => "Emergency Contact Telephone" %>
    <%= f.input :active, :label => "Active?", :as => :select, :collection => [["False", false], ["True", true]], :include_blank => false %>
  <% end %>
  <%= f.buttons :commit %>
<% end %>

app/views/admin/notes/_form.html.erb
<%= semantic_form_for [:admin, @note] do |f| %>
  <%= f.inputs "Note Details" do %>
    <%= f.input :member, :include_blank => false %>
    <%= f.input :body, :label => "Note" %>
    <%= f.input :admin_user_id, :as => :hidden, :value => current_admin_user.id %>
  <% end %>
  <%= f.buttons :commit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pln</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>